# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
# BASED ON c:\Users\olive\Documents\Github-repos\Modular_3D_Printer\Kinematics_Prototype\SOFT\g431-master

function(add_st_target_properties TARGET_NAME)

target_compile_definitions(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:ASM>>:DEBUG>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:DEBUG>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:USE_HAL_DRIVER>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:STM32G431xx>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:USE_HAL_DRIVER>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:STM32G431xx>"
)

target_include_directories(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/core\\Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/drivers\\stm32g4xx_hal\\Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/drivers\\stm32g4xx_hal\\Inc\\Legacy>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/drivers\\cmsis\\Device\\ST\\STM32G4xx\\Include>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/drivers\\cmsis\\Include>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/app>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/drivers\\bsp>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/core\\Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/drivers\\stm32g4xx_hal\\Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/drivers\\stm32g4xx_hal\\Inc\\Legacy>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/drivers\\cmsis\\Device\\ST\\STM32G4xx\\Include>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/drivers\\cmsis\\Include>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/app>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/drivers\\bsp>"
)

target_compile_options(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:ASM>>:-g3>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:-g3>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:-g3>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:ASM>>:-g0>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:-g0>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:-g0>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:-Og>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:-Os>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:-Os>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:>"
    "$<$<CONFIG:Debug>:-mcpu=cortex-m4>"
    "$<$<CONFIG:Debug>:-mfpu=fpv4-sp-d16>"
    "$<$<CONFIG:Debug>:-mfloat-abi=hard>"
    "$<$<NOT:$<CONFIG:Debug>>:-mcpu=cortex-m4>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfpu=fpv4-sp-d16>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfloat-abi=hard>"
)

target_link_libraries(
    ${TARGET_NAME} PRIVATE
)

target_link_directories(
    ${TARGET_NAME} PRIVATE
)

target_link_options(
    ${TARGET_NAME} PRIVATE
    "$<$<CONFIG:Debug>:-mcpu=cortex-m4>"
    "$<$<CONFIG:Debug>:-mfpu=fpv4-sp-d16>"
    "$<$<CONFIG:Debug>:-mfloat-abi=hard>"
    "$<$<NOT:$<CONFIG:Debug>>:-mcpu=cortex-m4>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfpu=fpv4-sp-d16>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfloat-abi=hard>"
    -T
    "$<$<CONFIG:Debug>:${PROJECT_SOURCE_DIR}/core/STM32G431KBTX_FLASH.ld>"
    "$<$<NOT:$<CONFIG:Debug>>:${PROJECT_SOURCE_DIR}/STM32G431KBTX_FLASH.ld>"
)

target_sources(
    ${TARGET_NAME} PRIVATE
    "app\\kinematics.c"
    "app\\limit_switches_demo.c"
    "app\\limit_switches.c"
    "app\\main.c"
    "app\\parser.c"
    "app\\stepper_motor.c"
    "core\\Src\\stm32g4xx_it.c"
    "core\\Src\\syscalls.c"
    "core\\Src\\sysmem.c"
    "core\\Src\\system_stm32g4xx.c"
    "core\\Startup\\bootloader.c"
    "core\\Startup\\startup_stm32g431kbtx.s"
    "drivers\\bsp\\APDS9960\\stm32g4_apds9960_color_algo.c"
    "drivers\\bsp\\APDS9960\\stm32g4_apds9960.c"
    "drivers\\bsp\\BH1750FVI\\stm32g4_bh1750fvi.c"
    "drivers\\bsp\\BMP180\\stm32g4_bmp180.c"
    "drivers\\bsp\\DHT11\\stm32g4_dht11.c"
    "drivers\\bsp\\DS18B20\\stm32g4_ds18b20.c"
    "drivers\\bsp\\epaper\\Fonts\\stm32g4_epaper_font12.c"
    "drivers\\bsp\\epaper\\Fonts\\stm32g4_epaper_font16.c"
    "drivers\\bsp\\epaper\\Fonts\\stm32g4_epaper_font20.c"
    "drivers\\bsp\\epaper\\Fonts\\stm32g4_epaper_font24.c"
    "drivers\\bsp\\epaper\\Fonts\\stm32g4_epaper_font8.c"
    "drivers\\bsp\\epaper\\stm32g4_epaper_com.c"
    "drivers\\bsp\\epaper\\stm32g4_epaper_demo.c"
    "drivers\\bsp\\epaper\\stm32g4_epaper_if.c"
    "drivers\\bsp\\epaper\\stm32g4_epaper_imagedata.c"
    "drivers\\bsp\\epaper\\stm32g4_epaper_paint.c"
    "drivers\\bsp\\GPS\\stm32g4_gps.c"
    "drivers\\bsp\\HC-05\\stm32g4_hc05.c"
    "drivers\\bsp\\HC-SR04\\stm32g4_hcsr04.c"
    "drivers\\bsp\\LD19\\QS_maths.c"
    "drivers\\bsp\\LD19\\stm32g4_ld19_display.c"
    "drivers\\bsp\\LD19\\stm32g4_ld19.c"
    "drivers\\bsp\\MatrixKeyboard\\stm32g4_matrix_keyboard.c"
    "drivers\\bsp\\MCP23017\\stm32g4_mcp23017.c"
    "drivers\\bsp\\MCP23S17\\stm32g4_mcp23s17.c"
    "drivers\\bsp\\MotorDC\\stm32g4_motorDC.c"
    "drivers\\bsp\\MPU6050\\stm32g4_mpu6050.c"
    "drivers\\bsp\\NFC03A1\\CR95HF\\drv_95hf.c"
    "drivers\\bsp\\NFC03A1\\lib_nfc\\common\\lib_95HFConfigManager.c"
    "drivers\\bsp\\NFC03A1\\lib_nfc\\lib_NDEF\\lib_95HF_wrapper.c"
    "drivers\\bsp\\NFC03A1\\lib_nfc\\lib_NDEF\\lib_NDEF_AAR.c"
    "drivers\\bsp\\NFC03A1\\lib_nfc\\lib_NDEF\\lib_NDEF_Email.c"
    "drivers\\bsp\\NFC03A1\\lib_nfc\\lib_NDEF\\lib_NDEF_Geo.c"
    "drivers\\bsp\\NFC03A1\\lib_nfc\\lib_NDEF\\lib_NDEF_MyApp.c"
    "drivers\\bsp\\NFC03A1\\lib_nfc\\lib_NDEF\\lib_NDEF_SMS.c"
    "drivers\\bsp\\NFC03A1\\lib_nfc\\lib_NDEF\\lib_NDEF_Text.c"
    "drivers\\bsp\\NFC03A1\\lib_nfc\\lib_NDEF\\lib_NDEF_URI.c"
    "drivers\\bsp\\NFC03A1\\lib_nfc\\lib_NDEF\\lib_NDEF_Vcard.c"
    "drivers\\bsp\\NFC03A1\\lib_nfc\\lib_NDEF\\lib_NDEF.c"
    "drivers\\bsp\\NFC03A1\\lib_nfc\\lib_pcd\\lib_iso14443Apcd.c"
    "drivers\\bsp\\NFC03A1\\lib_nfc\\lib_pcd\\lib_iso14443Bpcd.c"
    "drivers\\bsp\\NFC03A1\\lib_nfc\\lib_pcd\\lib_iso15693pcd.c"
    "drivers\\bsp\\NFC03A1\\lib_nfc\\lib_pcd\\lib_iso18092pcd.c"
    "drivers\\bsp\\NFC03A1\\lib_nfc\\lib_pcd\\lib_iso7816pcd.c"
    "drivers\\bsp\\NFC03A1\\lib_nfc\\lib_pcd\\lib_nfctype1pcd.c"
    "drivers\\bsp\\NFC03A1\\lib_nfc\\lib_pcd\\lib_nfctype2pcd.c"
    "drivers\\bsp\\NFC03A1\\lib_nfc\\lib_pcd\\lib_nfctype3pcd.c"
    "drivers\\bsp\\NFC03A1\\lib_nfc\\lib_pcd\\lib_nfctype4pcd.c"
    "drivers\\bsp\\NFC03A1\\lib_nfc\\lib_pcd\\lib_nfctype5pcd.c"
    "drivers\\bsp\\NFC03A1\\lib_nfc\\lib_pcd\\lib_pcd.c"
    "drivers\\bsp\\NFC03A1\\stm32g4_nfc03a1.c"
    "drivers\\bsp\\SD\\FatFs\\src\\diskio.c"
    "drivers\\bsp\\SD\\FatFs\\src\\drivers\\sd_diskio.c"
    "drivers\\bsp\\SD\\FatFs\\src\\ff_gen_drv.c"
    "drivers\\bsp\\SD\\FatFs\\src\\ff.c"
    "drivers\\bsp\\SD\\FatFs\\src\\option\\ccsbcs.c"
    "drivers\\bsp\\SD\\FatFs\\src\\option\\syscall.c"
    "drivers\\bsp\\SD\\stm32g4_sd.c"
    "drivers\\bsp\\stm32g4_adc.c"
    "drivers\\bsp\\stm32g4_dac.c"
    "drivers\\bsp\\stm32g4_extit.c"
    "drivers\\bsp\\stm32g4_flash.c"
    "drivers\\bsp\\stm32g4_gpio.c"
    "drivers\\bsp\\stm32g4_i2c.c"
    "drivers\\bsp\\stm32g4_rtc.c"
    "drivers\\bsp\\stm32g4_spi.c"
    "drivers\\bsp\\stm32g4_sys.c"
    "drivers\\bsp\\stm32g4_systick.c"
    "drivers\\bsp\\stm32g4_timer.c"
    "drivers\\bsp\\stm32g4_uart.c"
    "drivers\\bsp\\tft_ili9341\\stm32g4_fonts.c"
    "drivers\\bsp\\tft_ili9341\\stm32g4_ili9341.c"
    "drivers\\bsp\\tft_ili9341\\stm32g4_xpt2046.c"
    "drivers\\bsp\\VL53L0X\\stm32g4_vl53l0x_demo.c"
    "drivers\\bsp\\VL53L0X\\vl53l0x_api_calibration.c"
    "drivers\\bsp\\VL53L0X\\vl53l0x_api_core.c"
    "drivers\\bsp\\VL53L0X\\vl53l0x_api_ranging.c"
    "drivers\\bsp\\VL53L0X\\vl53l0x_api_strings.c"
    "drivers\\bsp\\VL53L0X\\vl53l0x_api.c"
    "drivers\\bsp\\VL53L0X\\vl53l0x_platform_log.c"
    "drivers\\bsp\\VL53L0X\\vl53l0x_platform.c"
    "drivers\\bsp\\WS2812\\stm32g4_ws2812.c"
    "drivers\\bsp\\WS2812\\WS2812_asm.s"
    "drivers\\bsp\\YX6300\\stm32g4_yx6300.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_adc_ex.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_adc.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_cortex.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_dac_ex.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_dac.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_dma_ex.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_dma.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_exti.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_flash_ex.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_flash_ramfunc.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_flash.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_gpio.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_i2c_ex.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_i2c.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_pwr_ex.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_pwr.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_rcc_ex.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_rcc.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_rng.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_rtc_ex.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_rtc.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_spi_ex.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_spi.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_tim_ex.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_tim.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_uart_ex.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal_uart.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_hal.c"
    "drivers\\stm32g4xx_hal\\Src\\stm32g4xx_ll_adc.c"
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_SIZE} $<TARGET_FILE:${TARGET_NAME}>
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_OBJCOPY} -O ihex
    $<TARGET_FILE:${TARGET_NAME}> ${TARGET_NAME}.hex
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_OBJCOPY} -O binary
    $<TARGET_FILE:${TARGET_NAME}> ${TARGET_NAME}.bin
)

endfunction()